<a href="https://colab.research.google.com/github/Madathanapalleleena/ML_DL_Practice/blob/main/dl_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def AND(x1,x2):
  w1=1
  w2=1
  bias=-1.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
res=AND(0,0)
r2=AND(1,1)
R3=AND(1,0)
r4=AND(0,1)
print(res)
print(r4)
print(R3)
print(r2)

0
0
0
1


In [ ]:
def OR(x1,x2):
  w1=1
  w2=1
  bias=-0.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
res=OR(0,0)
r2=OR(1,1)
r3=OR(1,0)
r4=OR(0,1)
print(res)
print(r2)
print(r3)
print(r4)

0
1
1
1


In [ ]:
def NAND(x1,x2):
  w1=-1
  w2=-1
  bias=1.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
r1=NAND(0,0)
r2=NAND(0,1)
r3=NAND(1,0)
r4=NAND(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
1
1
0


In [ ]:
def XOR(x1,x2):
  h1=NAND(x1,x2)
  h2=OR(x1,x2)
  y=AND(h1,h2)
  return y
r1=XOR(0,0)
r2=XOR(0,1)
r3=XOR(1,0)
r4=XOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

0
1
1
0


In [ ]:
def NOR(x1,x2):
  w1=-1
  w2=-1
  bias=0.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
r1=NOR(0,0)
r2=NOR(0,1)
r3=NOR(1,0)
r4=NOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
0
0
0


In [ ]:
def XNOR(x1,x2):
  h1=NOR(x1,x2)
  h2=AND(x1,x2)
  y=OR(h1,h2)
  return y
r1=XNOR(0,0)
r2=XNOR(0,1)
r3=XNOR(1,0)
r4=XNOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
0
0
1


In [ ]:
#implement AND using perceptron
import numpy as np
def step(x):
  return 1 if x>=0 else 0
class perceptron:
  def __init__(self,weight,bias):
    self.weight=weight
    self.bias=bias
  def predict(self,inputs):
    total=np.dot(self.weight,inputs)+self.bias
    print("THRESHOLD VALUE:",total)
    return step(total)
weights=np.array([1,1])
bias=-1.5
p=perceptron(weights,bias)
print("AND")
print(p.predict([0,0]))
print(p.predict([0,1]))
print(p.predict([1,0]))
print(p.predict([1,1]))

AND
THRESHOLD VALUE: -1.5
0
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: 0.5
1


In [ ]:
weights=np.array([1,1])
bias=-0.5
p2=perceptron(weights,bias)
print("OR")
print(p2.predict([0,0]))
print(p2.predict([0,1]))
print(p2.predict([1,0]))
print(p2.predict([1,1]))

OR
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: 0.5
1
THRESHOLD VALUE: 0.5
1
THRESHOLD VALUE: 1.5
1


In [ ]:
#XOR- not possible with single perceptron
weights=np.array([1,1])
bias=-0.2
p3=perceptron(weights,bias)
print("AND")
print(p3.predict([0,0]))
print(p3.predict([0,1]))
print(p3.predict([1,0]))
print(p3.predict([1,1]))

AND
THRESHOLD VALUE: -0.2
0
THRESHOLD VALUE: 0.8
1
THRESHOLD VALUE: 0.8
1
THRESHOLD VALUE: 1.8
1


In [ ]:
#multi perceptron
def step(x):
  return 1 if x>=0 else 0
class mlp:
  def __init__(self):
    self.w1=np.array([1,1])
    self.b1=-1.5
    self.w2=np.array([1,1])
    self.b2=-0.5
    self.w3=np.array([-1,-1])
    self.b3=1.5
  def predict(self,inputs):
    self.h1=step(np.dot(self.w3,inputs)+self.b3)
    self.h2=step(np.dot(self.w2,inputs)+self.b2)
    self.o1=step(np.dot([self.h1,self.h2],self.w1)+self.b1)
    return self.o1
xor=mlp()
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(x,xor.predict(x))


(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 0


In [ ]:
#threshold logic used by perceptron
def step(x):
  return 1 if x>=0 else 0
class perceptron:
  def __init__(self,weights,bias):
    self.weights=weights
    self.bias=bias
  def predict(self,x):
    total=np.dot(self.weights,x)+self.bias
    print(x)
    print("THRESHOLD VALUE:",total)
    return step(total)
#small changes in input

weights=np.array([1,1])
bias=-1.0
p=perceptron(weights,bias)

inputs=np.array([0.49, 0.50])
print(p.predict(inputs))
i2=np.array([0.50, 0.50])
print(p.predict(i2))
i3=np.array([0.51, 0.50])
print(p.predict(i3))

[0.49 0.5 ]
THRESHOLD VALUE: -0.010000000000000009
0
[0.5 0.5]
THRESHOLD VALUE: 0.0
1
[0.51 0.5 ]
THRESHOLD VALUE: 0.010000000000000009
1


In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))
class perceptron:
  def __init__(self,weights,bias):
    self.weights=weights
    self.bias=bias
  def predict(self,x):
    total=np.dot(self.weights,x)+self.bias
    print(x)
    print("THRESHOLD VALUE:",total)
    return sigmoid(total)
#small changes in input

weights=np.array([1,1])
bias=-1.0
p=perceptron(weights,bias)

inputs=np.array([0.49, 0.50])
print(p.predict(inputs))
i2=np.array([0.50, 0.50])
print(p.predict(i2))
i3=np.array([0.51, 0.50])
print(p.predict(i3))

[0.49 0.5 ]
THRESHOLD VALUE: -0.010000000000000009
0.49750002083312495
[0.5 0.5]
THRESHOLD VALUE: 0.0
0.5
[0.51 0.5 ]
THRESHOLD VALUE: 0.010000000000000009
0.502499979166875


In [1]:
from google.colab import files
uploaded=files.upload()

Saving movie.csv to movie.csv


In [6]:
import numpy as np
import pandas as pd
df=pd.read_csv("movie.csv")
X = df.iloc[:, :-1].values   # f1, f2, f3, f4
y = df.iloc[:, -1].values   # label

print("Features:\n", X)
print("Labels:\n", y)

Features:
 [[1.   1.   1.   0.92]
 [1.   0.   0.   0.78]
 [0.   1.   1.   0.85]
 [0.   0.   0.   0.4 ]
 [1.   1.   0.   0.6 ]
 [0.   1.   0.   0.45]
 [0.   0.   1.   0.5 ]
 [1.   0.   1.   0.88]]
Labels:
 [1 1 1 0 1 0 0 1]


In [7]:
def mp_perceptron(x, threshold):
    return 1 if np.sum(x) >= threshold else 0

print("\nMP Perceptron Output:")
threshold = X.shape[1]

for i in range(len(X)):
    pred = mp_perceptron(X[i], threshold)
    print(f"Sample {i+1}: Pred={pred}, Actual={y[i]}")



MP Perceptron Output:
Sample 1: Pred=0, Actual=1
Sample 2: Pred=0, Actual=1
Sample 3: Pred=0, Actual=1
Sample 4: Pred=0, Actual=0
Sample 5: Pred=0, Actual=1
Sample 6: Pred=0, Actual=0
Sample 7: Pred=0, Actual=0
Sample 8: Pred=0, Actual=1


In [8]:
def train_perceptron_no_bias(X, y, lr=0.1, epochs=10):
    weights = np.zeros(X.shape[1])

    for epoch in range(epochs):
        for i in range(len(X)):
            net = np.dot(X[i], weights)
            pred = 1 if net >= 0 else 0
            error = y[i] - pred
            weights += lr * error * X[i]

    return weights

weights_no_bias = train_perceptron_no_bias(X, y)

print("\nWeights (No Bias):", weights_no_bias)



Weights (No Bias): [ 0.2    0.     0.    -0.147]


In [9]:
test_movie = np.array([1, 1, 0, 0.75])
print("Prediction (No Bias):", np.dot(test_movie, weights_no_bias) >= 0)


Prediction (No Bias): True


In [10]:
def train_perceptron(X, y, lr=0.1, epochs=10):
    weights = np.zeros(X.shape[1])
    bias = 0

    for epoch in range(epochs):
        for i in range(len(X)):
            net = np.dot(X[i], weights) + bias
            pred = 1 if net >= 0 else 0
            error = y[i] - pred

            weights += lr * error * X[i]
            bias += lr * error

    return weights, bias

weights, bias = train_perceptron(X, y)

print("\nWeights:", weights)
print("Bias:", bias)



Weights: [0.3   0.1   0.2   0.116]
Bias: -0.30000000000000004


In [11]:
import numpy as np
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
functions = {
    "f1":  [0,0,0,0],
    "f2":  [0,0,0,1], #AND
    "f3":  [0,0,1,0],
    "f4":  [0,0,1,1],
    "f5":  [0,1,0,0],
    "f6":  [0,1,0,1],
    "f7":  [0,1,1,0], #XOR
    "f8":  [0,1,1,1],
    "f9":  [1,0,0,0],
    "f10": [1,0,0,1],#XNOR
    "f11": [1,0,1,0],
    "f12": [1,0,1,1],
    "f13": [1,1,0,0],
    "f14": [1,1,0,1],
    "f15": [1,1,1,0],
    "f16": [1,1,1,1]
}


In [12]:
def train_perceptron(X, y, lr=0.1, epochs=50):
    weights = np.zeros(X.shape[1])
    bias = 0

    for _ in range(epochs):
        errors = 0
        for i in range(len(X)):
            net = np.dot(X[i], weights) + bias
            pred = 1 if net >= 0 else 0
            error = y[i] - pred
            if error != 0:
                weights += lr * error * X[i]
                bias += lr * error
                errors += 1
        if errors == 0:
            return True  # Converged
    return False  # Did not converge


In [13]:
linearly_separable = []
not_separable = []

for name, y_vals in functions.items():
    y = np.array(y_vals)
    if train_perceptron(X, y):
        linearly_separable.append(name)
    else:
        not_separable.append(name)

print("Linearly separable functions:")
print(linearly_separable)

print("\nNot linearly separable functions:")
print(not_separable)


Linearly separable functions:
['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f8', 'f9', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16']

Not linearly separable functions:
['f7', 'f10']


In [18]:
def step(x):
    return 1 if x >= 0 else 0
import numpy as np


def hidden_layer(x1, x2):
    h1 = step(-x1 - x2 + 0.5)
    h2 = step(-x1 + x2 - 0.5)
    h3 = step( x1 - x2 - 0.5)
    h4 = step( x1 + x2 - 1.5)
    return [h1, h2, h3, h4]


In [19]:
def mlp_boolean(x1, x2, f):
    h = hidden_layer(x1, x2)
    weights = np.array(f)
    bias = -0.5
    net = np.dot(weights, h) + bias
    return step(net)


In [20]:
AND = [0, 0, 0, 1]
inputs = [(0,0), (0,1), (1,0), (1,1)]

print("AND Function:")
for x in inputs:
    print(x, "→", mlp_boolean(x[0], x[1], AND))


AND Function:
(0, 0) → 0
(0, 1) → 0
(1, 0) → 0
(1, 1) → 1


In [21]:
XOR = [0, 1, 1, 0]

print("\nXOR Function:")
for x in inputs:
    print(x, "→", mlp_boolean(x[0], x[1], XOR))



XOR Function:
(0, 0) → 0
(0, 1) → 1
(1, 0) → 1
(1, 1) → 0
