<a href="https://colab.research.google.com/github/Madathanapalleleena/ML_LAB_Practice/blob/main/dl_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def AND(x1,x2):
  w1=1
  w2=1
  bias=-1.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
res=AND(0,0)
r2=AND(1,1)
R3=AND(1,0)
r4=AND(0,1)
print(res)
print(r4)
print(R3)
print(r2)

0
0
0
1


In [ ]:
def OR(x1,x2):
  w1=1
  w2=1
  bias=-0.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
res=OR(0,0)
r2=OR(1,1)
r3=OR(1,0)
r4=OR(0,1)
print(res)
print(r2)
print(r3)
print(r4)

0
1
1
1


In [ ]:
def NAND(x1,x2):
  w1=-1
  w2=-1
  bias=1.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
r1=NAND(0,0)
r2=NAND(0,1)
r3=NAND(1,0)
r4=NAND(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
1
1
0


In [ ]:
def XOR(x1,x2):
  h1=NAND(x1,x2)
  h2=OR(x1,x2)
  y=AND(h1,h2)
  return y
r1=XOR(0,0)
r2=XOR(0,1)
r3=XOR(1,0)
r4=XOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

0
1
1
0


In [ ]:
def NOR(x1,x2):
  w1=-1
  w2=-1
  bias=0.5
  activation=w1*x1+w2*x2+bias
  if activation>0:
    return 1
  else:
    return 0
r1=NOR(0,0)
r2=NOR(0,1)
r3=NOR(1,0)
r4=NOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
0
0
0


In [ ]:
def XNOR(x1,x2):
  h1=NOR(x1,x2)
  h2=AND(x1,x2)
  y=OR(h1,h2)
  return y
r1=XNOR(0,0)
r2=XNOR(0,1)
r3=XNOR(1,0)
r4=XNOR(1,1)
print(r1)
print(r2)
print(r3)
print(r4)

1
0
0
1


In [ ]:
#implement AND using perceptron
import numpy as np
def step(x):
  return 1 if x>=0 else 0
class perceptron:
  def __init__(self,weight,bias):
    self.weight=weight
    self.bias=bias
  def predict(self,inputs):
    total=np.dot(self.weight,inputs)+self.bias
    print("THRESHOLD VALUE:",total)
    return step(total)
weights=np.array([1,1])
bias=-1.5
p=perceptron(weights,bias)
print("AND")
print(p.predict([0,0]))
print(p.predict([0,1]))
print(p.predict([1,0]))
print(p.predict([1,1]))

AND
THRESHOLD VALUE: -1.5
0
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: 0.5
1


In [ ]:
weights=np.array([1,1])
bias=-0.5
p2=perceptron(weights,bias)
print("OR")
print(p2.predict([0,0]))
print(p2.predict([0,1]))
print(p2.predict([1,0]))
print(p2.predict([1,1]))

OR
THRESHOLD VALUE: -0.5
0
THRESHOLD VALUE: 0.5
1
THRESHOLD VALUE: 0.5
1
THRESHOLD VALUE: 1.5
1


In [ ]:
#XOR- not possible with single perceptron
weights=np.array([1,1])
bias=-0.2
p3=perceptron(weights,bias)
print("AND")
print(p3.predict([0,0]))
print(p3.predict([0,1]))
print(p3.predict([1,0]))
print(p3.predict([1,1]))

AND
THRESHOLD VALUE: -0.2
0
THRESHOLD VALUE: 0.8
1
THRESHOLD VALUE: 0.8
1
THRESHOLD VALUE: 1.8
1


In [ ]:
#multi perceptron
def step(x):
  return 1 if x>=0 else 0
class mlp:
  def __init__(self):
    self.w1=np.array([1,1])
    self.b1=-1.5
    self.w2=np.array([1,1])
    self.b2=-0.5
    self.w3=np.array([-1,-1])
    self.b3=1.5
  def predict(self,inputs):
    self.h1=step(np.dot(self.w3,inputs)+self.b3)
    self.h2=step(np.dot(self.w2,inputs)+self.b2)
    self.o1=step(np.dot([self.h1,self.h2],self.w1)+self.b1)
    return self.o1
xor=mlp()
for x in [(0,0),(0,1),(1,0),(1,1)]:
  print(x,xor.predict(x))


(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 0


In [ ]:
#threshold logic used by perceptron
def step(x):
  return 1 if x>=0 else 0
class perceptron:
  def __init__(self,weights,bias):
    self.weights=weights
    self.bias=bias
  def predict(self,x):
    total=np.dot(self.weights,x)+self.bias
    print(x)
    print("THRESHOLD VALUE:",total)
    return step(total)
#small changes in input

weights=np.array([1,1])
bias=-1.0
p=perceptron(weights,bias)

inputs=np.array([0.49, 0.50])
print(p.predict(inputs))
i2=np.array([0.50, 0.50])
print(p.predict(i2))
i3=np.array([0.51, 0.50])
print(p.predict(i3))

[0.49 0.5 ]
THRESHOLD VALUE: -0.010000000000000009
0
[0.5 0.5]
THRESHOLD VALUE: 0.0
1
[0.51 0.5 ]
THRESHOLD VALUE: 0.010000000000000009
1


In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))
class perceptron:
  def __init__(self,weights,bias):
    self.weights=weights
    self.bias=bias
  def predict(self,x):
    total=np.dot(self.weights,x)+self.bias
    print(x)
    print("THRESHOLD VALUE:",total)
    return sigmoid(total)
#small changes in input

weights=np.array([1,1])
bias=-1.0
p=perceptron(weights,bias)

inputs=np.array([0.49, 0.50])
print(p.predict(inputs))
i2=np.array([0.50, 0.50])
print(p.predict(i2))
i3=np.array([0.51, 0.50])
print(p.predict(i3))

[0.49 0.5 ]
THRESHOLD VALUE: -0.010000000000000009
0.49750002083312495
[0.5 0.5]
THRESHOLD VALUE: 0.0
0.5
[0.51 0.5 ]
THRESHOLD VALUE: 0.010000000000000009
0.502499979166875


In [ ]:
from google.colab import files
uploaded=files.upload()

Saving movie.csv to movie.csv


In [ ]:
import numpy as np
import pandas as pd

def step(x):
    return 1 if x >= 0 else 0

class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=20):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = 0

    def predict(self, x):
        return step(np.dot(x, self.weights) + self.bias)

    def train(self, X, y):
        self.weights = np.zeros(X.shape[1])

        for epoch in range(self.epochs):
            errors = 0
            print(f"\nEpoch {epoch + 1}")

            for i in range(len(X)):
                y_pred = self.predict(X[i])
                error = y[i]- y_pred

                if error != 0:
                    self.weights += self.lr * error * X[i]
                    self.bias += self.lr * error
                    errors += 1

                    print(f"Updated weights: {self.weights}, Bias: {self.bias}")

            print(f"Epoch {epoch + 1} errors: {errors}")
            if errors == 0:
                print("Convergence")
                break

In [ ]:
import numpy as np
import pandas as pd

def step(x):
    return 1 if x >= 0 else 0

class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=20):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = 0

    def predict(self, x):
        return step(np.dot(x, self.weights) + self.bias)

    def train(self, X, y):
        self.weights = np.zeros(X.shape[1])

        for epoch in range(self.epochs):
            errors = 0
            print(f"\nEpoch {epoch + 1}")

            for i in range(len(X)):
                y_pred = self.predict(X[i])
                error = y[i]- y_pred

                if error != 0:
                    self.weights += self.lr * error * X[i]
                    self.bias += self.lr * error
                    errors += 1

                    print(f"Updated weights: {self.weights}, Bias: {self.bias}")

            print(f"Epoch {epoch + 1} errors: {errors}")
            if errors == 0:
                print("Convergence")
                break

In [ ]:
#without weights and bias
data = pd.read_csv("movie.csv")
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print("Features:",X)
print("Labels:",y)
p=Perceptron(learning_rate=0.1,epochs=25)
p.train(X,y)

In [ ]:
data = pd.read_csv("movie.csv")

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
print("Features:", X)
print("Labels:", y)

p = Perceptron(learning_rate=0.1, epochs=25)
p.train(X, y)

print("Final Weights:", p.weights)
print("Final Bias:", p.bias)

Features: [[1.   1.   1.   0.92]
 [1.   0.   0.   0.78]
 [0.   1.   1.   0.85]
 [0.   0.   0.   0.4 ]
 [1.   1.   0.   0.6 ]
 [0.   1.   0.   0.45]
 [0.   0.   1.   0.5 ]
 [1.   0.   1.   0.88]]
Labels: [1 1 1 0 1 0 0 1]

Epoch 1
Updated weights: [ 0.    0.    0.   -0.04], Bias: -0.1
Updated weights: [0.1  0.1  0.   0.02], Bias: 0.0
Updated weights: [ 0.1    0.     0.    -0.025], Bias: -0.1
Updated weights: [0.2   0.    0.1   0.063], Bias: 0.0
Epoch 1 errors: 4

Epoch 2
Updated weights: [0.2   0.    0.1   0.023], Bias: -0.1
Updated weights: [ 0.2    0.     0.    -0.027], Bias: -0.2
Updated weights: [0.3   0.    0.1   0.061], Bias: -0.1
Epoch 2 errors: 3

Epoch 3
Updated weights: [0.3   0.    0.    0.011], Bias: -0.2
Epoch 3 errors: 1

Epoch 4
Updated weights: [0.3   0.1   0.1   0.096], Bias: -0.1
Updated weights: [0.3   0.    0.1   0.051], Bias: -0.2
Epoch 4 errors: 2

Epoch 5
Updated weights: [0.3   0.1   0.2   0.136], Bias: -0.1
Updated weights: [0.3   0.    0.2   0.091], Bias: -0.2
